# This workflow calculates size diffs for the compiled binary of each supported tock board

name: Benchmarks

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on:
  pull_request:
    branches: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# If you add additional jobs, remember to add them to bors.toml
jobs:
  benchmarks:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1 # pulls version from rust-toolchain file
        with:
          components: rustfmt, clippy
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --user cxxfilt
          sudo apt install llvm
      - name: size report
        run: |
          ./tools/github_actions_size_changes
